name: Customer service
description: This is the description of the service to individual customer resources
style: RESOURCE
uriTemplate: /customers/{id}
methods:
    GET:
        summary: Get one customer
        notes: Get one customer
        # implementation: api.getCustomer
        request:
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: &OkStatusCode 200
                reason: &OkReason Successful execution
                validationSchema: getCustomer-responseBody-validationSchema.json
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: getCustomer-responseBody.json
        testCases:
            -
                name: Get Customer
                description: Successfully retrieves one customer
                url: /customers/1
                template: testGetMethod.mustache
                request:
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    # validationSchema: customer.json

    DELETE:
        summary: Delete a customer
        notes: Delete a customer
        # implementation: api.deleteCustomer
        request:
            parameters: 
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the customer record to be deleted
                    default: 1
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: deleteCustomer-responseBody-validationSchema.json
                headers:
                    -
                        field: Content-Type
                        content: application/json
        testCases:
            -
                name: Delete Customer
                description: Successfully delete the customer
                url: /customers/1
                template: testDelMethod.mustache
                request:
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"

    PUT:
        summary: Update a customer
        notes: Update a customer
        # implementation: api.putCustomer
        request:
            parameters:
                -
                    name: id
                    kind: QUERY
                    required: true
                    type: number
                    summary: The id of the customer record to be updated
                    default: 1
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: *OkStatusCode
                reason: *OkReason
                # validationSchema: putCustomer-responseBody-validationSchema.json
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: putCustomer-responseBody.json
        testCases:
            -
                name: Update Customer
                description: Succesfully updates a customer
                url: /customers/1
                template: testPutMethod.mustache
                request:
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: putCustomer-requestBody.json
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    validationSchema: putCustomer-responseBody-validationSchema.json
