name: Customer service
description: This is the description of the service to individual customer resources
style: RESOURCE
urlPattern: /customers/{id}
methods:
    GET:
        summary: Get one customer
        notes:
        implementation: api.getCustomer
        request:
            parameters: []
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: 200
                reason: Successful execution
                # validationSchema: getCustomer-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                    -
                        field: X-Application-Version
                        content: v0.4 # This value must be parametric
                    -
                        field: X-Application-API-Version
                        content: v0.1 # This value must be parametric
                # mockBody: getCustomer-responseBody.json
        testCases:
            -
                name: Get Customer
                description: Successfully retrieves one customer
                url: /customers/1
                template: testGetMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    statusCode: 200
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    # validationSchema: customer.json

    DELETE:
        summary: Delete a customer
        notes:
        implementation: api.deleteCustomer
        request:
            parameters: [{"name": "id", "kind": "QUERY", "required": true, "type": "integer", "summary": "The id of the customer record to be deleted", "default": 1}]
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: 200
                reason: Successful execution
                # validationSchema: deleteCustomer-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                    -
                        field: X-Application-Version
                        content: v0.4 # This value must be parametric
                    -
                        field: X-Application-API-Version
                        content: v0.1 # This value must be parametric
        testCases:
            -
                name: Delete Customer
                description: Successfully delete the customer
                url: /customers/1
                template: testDelMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                response:
                    statusCode: 200
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"

    PUT:
        summary: Update a customer
        notes:
        implementation: api.putCustomer
        request:
            parameters: [{"name": "id", "kind": "QUERY", "required": true, "type": "integer", "summary": "The id of the customer record to be updated", "default": 1}]
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
        responses:
            -
                name: OK
                statusCode: 200
                reason: Successful execution
                # validationSchema: putCustomer-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                    -
                        field: X-Application-Version
                        content: v0.4 # This value must be parametric
                    -
                        field: X-Application-API-Version
                        content: v0.1 # This value must be parametric
                # mockBody: putCustomer-responseBody.json
        testCases:
            -
                name: Update Customer
                description: Succesfully updates a customer
                url: /customers/1
                template: testPutMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: putCustomer-requestBody.json
                response:
                    statusCode: 200
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    # validationSchema: customer.json
